project:
  type: website

website:
  title: "Paul Smith"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - href: https://pws3141.github.io/blog/
        text: Blog
        icon: newspaper
      - href: https://github.com/pws3141
        icon: github

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

